### ISSUE TITLE
INCREMENTAL replication is extracting same data each run with no changes

### ISSUE THREAD

**Issue by dluo-sig** [wintersrd/pipelinewise-tap-mssql#78]
My configuration:

```
    metadata:
      dbo-*:
        replication-method: INCREMENTAL
        table-key-properties: [ Id ]
        replication-key: UpdatedAt
```

UpdatedAt is of type datetime2 (not sure if relevant).  To reproduce, I started with no state and no existing table.  The first run did a full load, as expected.  A second run with no changes to the data resulted in one new record, the one with the max value of UpdatedAt. If there are multiple records with the same max value, they are all extracted.  I would have expected no records as there were no changes to the data.  It should only check for records with a greater value, rather than greater or equal to.  Not sure if there's some edge case that I'm missing and this is intended or not.
